### ISSUE TITLE
about setup

### ISSUE THREAD

**Issue by b856741** [TinfoilHat0/Defending-Against-Backdoors-with-Robust-Learning-Rate#3]
hi,when I tried to run `python federated.py --data=fmnist --local_ep=2 --bs=256 --num_agents=10 --rounds=200` 
there is a problem show up
![err](https://user-images.githubusercontent.com/22851308/182599447-68fa1b1c-cbc9-45fc-90df-cfbf9105e1a8.PNG)
do you have any ideas about it ?

**Comment by TinfoilHat0** [comment]
Hi,

It looks like this error occurs due to tensorboard. Can you try commenting out tensorboard stuff, and try again?
If it works, I'd guess the error is due to some tensorboard version conflict between tensorflow and pytorch.

**Comment by b856741** [comment]
Thanks a lot for replying.
I don't know if I commented the correct line
![Try1](https://user-images.githubusercontent.com/22851308/182667851-e446eb70-96c0-4093-94b3-34ae621d51dd.PNG)
but after I commented this line, there's a new problem showed up.
![try1err](https://user-images.githubusercontent.com/22851308/182667968-eb9929b8-2950-4398-b8ad-8f5ef888229e.PNG)

**Comment by TinfoilHat0** [comment]
You’ve to comment out all summarywriter events, not just the import.

**Comment by b856741** [comment]
Hi,I tried to comment all summarywriter ,and writer,but it seems "writer" is a necessary part.
do you have else ideas? Thanks
![try2](https://user-images.githubusercontent.com/22851308/183119029-dce87243-225d-4667-b793-0d90b4c0f132.PNG)
![try2err](https://user-images.githubusercontent.com/22851308/183119080-51b0d568-aa40-407f-908d-6509404db2d9.PNG)

**Comment by TinfoilHat0** [comment]
Just try setting writer=None, and comment out wherever writer is used maybe? The other solution is to simply solve the version conflict. You can try creating another environment without tensorflow, and just install pytorch and its version of tensorboard.

**Comment by TinfoilHat0** [comment]
Closing as this is a package conflict
